artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/Subash7Lingden/repository-cat-vs-dog/raw/main/zip_recommender%20system.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data
